// <auto-generated />
using MVC_DataHandling.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_DataHandling.Migrations
{
    [DbContext(typeof(MVCCoreDbContext))]
    [Migration("20250702050336_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_DataHandling.Models.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("Money");

                    b.Property<string>("City")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("Varchar");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("CustId");

                    b.ToTable("Customers");
                });
#pragma warning restore 612, 618
        }
    }
}
